version: '3.9'
services:
  # Apache webserver service
  webserver:
    container_name: PHP-webServer
    build:
      # Dockerfile path
      context: .
      dockerfile: Dockerfile
    # Mount the local ./app directory to /var/www/html in the container
    volumes:
      - ./app:/var/www/html 
    # Map port 8000 on the host to port 80 on the container 
    ports:
      - 8000:80  
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Define volume for PostgreSQL data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      # Default email for pgAdmin 4
      PGADMIN_DEFAULT_EMAIL: new@gmail.com
      # Password for accessing pgAdmin 4
      PGADMIN_DEFAULT_PASSWORD: 2329new
    ports:
      # Expose pgadmin on 5050 
      - "5051:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always

volumes:
  pgadmin_data:
  postgres_data:   # Define volume for PostgreSQL data
