# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegisterTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registerTest(self):
    self.driver.get("http://localhost:8000/index.php")
    self.driver.set_window_size(1070, 816)
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "first_name").click()
    self.driver.find_element(By.ID, "first_name").send_keys("Praveena")
    self.driver.find_element(By.ID, "last_name").click()
    self.driver.find_element(By.ID, "last_name").send_keys("R")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("21bcaf44@kristujayanti.com")
    self.driver.find_element(By.ID, "phone_number").click()
    self.driver.find_element(By.ID, "phone_number").send_keys("8217830611")
    self.driver.find_element(By.ID, "emergency_contact_name").click()
    self.driver.find_element(By.ID, "emergency_contact_name").send_keys("Paul")
    self.driver.find_element(By.ID, "emergency_contact_phone").click()
    self.driver.find_element(By.ID, "emergency_contact_phone").send_keys("9108800104")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("abcdef")
    self.driver.find_element(By.ID, "date_of_birth").click()
    self.driver.find_element(By.ID, "date_of_birth").send_keys("2024-05-06")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("2329")
    self.driver.find_element(By.ID, "degree").click()
    self.driver.find_element(By.ID, "degree").send_keys("BCA")
    self.driver.find_element(By.ID, "major").click()
    self.driver.find_element(By.ID, "major").send_keys("Computer Science")
    self.driver.find_element(By.ID, "institution").click()
    self.driver.find_element(By.ID, "institution").send_keys("kristu jayanti college")
    self.driver.find_element(By.ID, "start_date").click()
    self.driver.find_element(By.ID, "start_date").send_keys("2024-05-15")
    self.driver.find_element(By.ID, "end_date").click()
    self.driver.find_element(By.ID, "end_date").click()
    self.driver.find_element(By.ID, "end_date").send_keys("2024-05-18")
    self.driver.find_element(By.ID, "skill_name").click()
    self.driver.find_element(By.ID, "skill_name").send_keys("coding")
    self.driver.find_element(By.ID, "proficiency").click()
    self.driver.find_element(By.ID, "proficiency").send_keys("java")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(33)").click()
  
