# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDocumenttest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_documenttest(self):
    self.driver.get("http://localhost:8000/dashboard.php")
    self.driver.set_window_size(1068, 816)
    self.driver.find_element(By.LINK_TEXT, "Document Management").click()
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("new")
    self.driver.find_element(By.NAME, "description").click()
    self.driver.find_element(By.NAME, "description").send_keys("sample")
    self.driver.find_element(By.NAME, "file").click()
    self.driver.find_element(By.NAME, "file").send_keys("C:\\fakepath\\meena_final.docx")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Back to Dashboard").click()
  
